name: Build
on: [push]

jobs:
  package:
    runs-on: ubuntu-latest
    container:
      image: wonderlandengine/editor:edge
    steps:
    - uses: actions/checkout@v2
    - name: Package
      run: |
        apt install -y zip

        # Build all node libraries
        cd ar-tracking && npm i && npm run build && cd ..
        cd ar-provider-webxr && npm i && npm run build && cd ..
        cd ar-provider-8thwall && npm i && npm run build && cd ..
        cd examples/common-components && npm i && cd ../..

        # Build all examples
        mkdir public
        cd examples
        for project in * ; do
          if [ ! -d "$project" ]; then continue; fi
          if [ "$project" = ".github" ]; then continue; fi
          if [ "$project" = "public" ]; then continue; fi
          if [ "$project" = "common-components" ]; then continue; fi

          echo "Zipping $project"
          zip -r ../public/$project.zip $project

          echo "Building $project"
          for projectFile in $project/*.wlp ; do
            /usr/local/bin/entrypoint.sh WonderlandEditor --credentials "$WLE_CREDENTIALS" --windowless --package --project ./$projectFile --output ../public/
          done
          mv ../public/index.html ../public/$project.html
        done
        cd ..
      env:
          WLE_CREDENTIALS: ${{ secrets.WLE_CREDENTIALS }}
    - name: Gzip
      run: gzip -k public/**/*.*
    - name: Upload package artifact
      uses: actions/upload-artifact@v2
      with:
        name: wonderland-engine-examples-deploy
        path: public/
  deploy-pages:
    needs: package
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download package artifact
      uses: actions/download-artifact@v2
      with:
        name: wonderland-engine-examples-deploy
        path: public/
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: public
  deploy-bucket:
    needs: package
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Download package artifact
      uses: actions/download-artifact@v2
      with:
        name: wonderland-engine-examples-deploy
        path: public/
    - name: Deploy static site to S3 bucket
      uses: BetaHuhn/do-spaces-action@v2
      with:
        source: './public/'
        out_dir: 'examples'
        space_name: ${{ secrets.AWS_NAME }}
        space_region: ${{ secrets.AWS_REGION}}
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
